### PR TITLE
(doc) complete press release

### PR DESCRIPTION
**Pull request by tournetorres**

### CODE REVIEW

**Review by dweill — COMMENTED** [review]
Branch the roots of your community- what does this mean?
there 's a typo on line 24. the word credentials is missing an n.

**Comment by tournetorres** [comment]
I was looking for a Tree themed slogan - doesn’t have to be this - thought something along the same lines as this would be cute - we may end up finding a good one towards the end - 

Or like - connect to the branches of your community  - or something -

**Comment by dweill** [comment]
Tree themed is great but branches and roots are literally the opposite parts of a tree. Maybe something like, Voluntree, where helping out is low hanging fruit. idk

**Comment by tournetorres** [comment]
I kind of love that - but I read this: and it sort of changed how I felt about writing slogans - https://medium.com/startup-grind/people-dont-buy-products-they-buy-better-versions-of-themselves-2ce85fdb5ff1 <https://medium.com/startup-grind/people-dont-buy-products-they-buy-better-versions-of-themselves-2ce85fdb5ff1> - easy, quick, empowering, read

**Pull request merged**
